service: my-special-service # NOTE: update this with your service name

custom:
  tableName: 'users-dbtable-serverless-${self:provider.stage}'  


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}



functions:
  hello:
    handler: handler.hello
    events:
     - http:
          path: /
          method: ANY
  addUser: 
    handler: handler.addUser
    events:
      - http: 
          path: user
          method: POST
  getUser: 
    handler: handler.getUser
    events:
      - http: 
          path: /user
          method: GET

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
